version: '3.3'

services:
  db:
    build:
      context: ./db
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app_net

  web:
    build:
      context: ./app
    restart: always
    expose:
      - "8000"
    volumes:
      - "D:\\jackson\\dev\\django\\planos-sim_internet\\app:/home/app/webapp"
      # - "D:\\jackson\\dev\\django\\planos-sim_internet\\app:/home/app/webapp"
    networks:
      - app_net
    command: >
      bash -c "pip install -r requeriments.txt && 
      /usr/src/app/init.sh"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_net
    volumes:
      - ./app/staticfiles:/home/app/webapp/staticfiles

networks:
  app_net:
    driver: bridge

# volumes:
#   app_data:
